apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
      - image: aishasemerci/resultserver 
        name: resultserver
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret



# - name: MYSQL_DATABASE_HOST
#   value: mysql-service  #dikkat burada mysql'in service adini giriyoruz!
# - name: MYSQL_DATABASE
#   value: "phonebook"
# - name: MYSQL_USER
#   value: "ayse"
# - name: MYSQL_PASSWORD 
#   value: "ayse1234" 