- name: configure nodejs instance 
  hosts: _ansible_nodejs
  become: true 
  tasks: 
    - name: create build directory
      file: 
        path: /home/ec2-user/nodejs 
        state: directory 
        owner: root 
        group: root 
        mode: "0755"  
 # at this point do not forget change DB_HOST env variable for postgresql node
    - name: copy files to nodejs node
      copy: 
        src: /home/ec2-user/ansible-project/nodejs/server/ # *** "/" dont forget
        dest: /home/ec2-user/nodejs   

    - name: copy the dockerfile
      copy: 
        src: /home/ec2-user/ansible-project/nodejs/Dockerfile
        dest: /home/ec2-user/nodejs 

    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name=ayse_nodejs' && docker stop ayse_nodejs && docker rm -fv ayse_nodejs && docker image rm -f aishasemerci/nodejs || echo 'Not Found'" 

    - name: build container image
      docker_image:
        name: aishasemerci/nodejs
        build: 
          path: /home/ec2-user/nodejs   
        source: build
        state: present         
# docker build -t aishasemerci/nodejs .  

    - name: create nodejs docker container
      docker_container:
        name: ayse_nodejs
        image: aishasemerci/nodejs
        state: started
        ports: 
          - "5000:5000" 
      register: container_info #in order to get output

    - name: print the container info
      debug: 
        var: container_info #publishing this output which we created above     

# run this playbook with "ansible-playbook docker_nodejs.yml" command
# you can check docker container and image with " ansible _ansible_nodejs -a "docker ps -a" " command!